# Generated by Django 4.0.5 on 2022-07-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_rename_edad_curso_camada_rename_nombre_curso_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='nombre',
        ),
    ]
